import fs from "fs";

function parse(file) {
  const svg = fs.readFileSync(file, "utf8");
  const d = svg
    .match(/<path d="([^"]+)"/)[1]
    .replace(/\s+/g, " ")
    .trim();
  // Tight content bbox (potrace keeps the input bitmap size as viewBox).
  const nums = d.match(/-?\d+\.?\d*/g).map(Number);
  const xs = [];
  const ys = [];
  for (let i = 0; i + 1 < nums.length; i += 2) {
    xs.push(nums[i]);
    ys.push(nums[i + 1]);
  }
  const p = 1;
  const minX = Math.min(...xs) - p;
  const minY = Math.min(...ys) - p;
  const w = Math.max(...xs) - Math.min(...xs) + 2 * p;
  const h = Math.max(...ys) - Math.min(...ys) + 2 * p;
  const vb = `${minX.toFixed(2)} ${minY.toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)}`;
  return { vb, d };
}

const full = parse("public/logo.svg");
const mark = parse("public/logo-mark.svg");

const out = `/**
 * Yantrava Labs logo — vector-traced from the source artwork (public/logo3.png via
 * potrace). \`Logo\` is the full lockup (mark + wordmark) at the designer's native
 * proportions; \`LogoMark\` is the mark alone (used for the favicon). Single even-odd
 * path each, so the inner-line detail survives as holes. Monotone via
 * \`currentColor\`. Size by height (e.g. \`h-10 w-auto\`). Decorative; callers supply
 * the accessible name.
 *
 * Generated by .genlogo.mjs — do not hand-edit. Re-run after re-tracing.
 */

export function Logo({ className = "" }: { className?: string }) {
  return (
    <svg viewBox="${full.vb}" fill="none" aria-hidden="true" className={className}>
      <path d="${full.d}" fill="currentColor" fillRule="evenodd" />
    </svg>
  );
}

export function LogoMark({ className = "" }: { className?: string }) {
  return (
    <svg viewBox="${mark.vb}" fill="none" aria-hidden="true" className={className}>
      <path d="${mark.d}" fill="currentColor" fillRule="evenodd" />
    </svg>
  );
}
`;

fs.writeFileSync("src/components/ui/logo.tsx", out);

// Favicon — the mark, bone on a dark rounded square (works on any tab colour).
{
  const m = parse("public/logo-mark.svg");
  const [minX, minY, w, h] = m.vb.split(" ").map(Number);
  const S = 512;
  const pad = 96;
  const avail = S - 2 * pad;
  const scale = Math.min(avail / w, avail / h);
  const tx = (S - w * scale) / 2 - minX * scale;
  const ty = (S - h * scale) / 2 - minY * scale;
  const icon = `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"><rect width="512" height="512" rx="112" fill="#0a0a0b"/><path transform="translate(${tx.toFixed(2)} ${ty.toFixed(2)}) scale(${scale.toFixed(4)})" d="${m.d}" fill="#f4f3ef" fill-rule="evenodd"/></svg>`;
  fs.writeFileSync("src/app/icon.svg", icon);
}

console.log(`wrote logo.tsx + icon.svg — full=${full.vb}, mark=${mark.vb}`);
